### ISSUE TITLE
User-story-1: List all addresses 

### ISSUE THREAD

**Issue by kchia** [Kiresorg/amex-demo-server#1]
# User-story-1: List all addresses
As a CSR, I would like to view a list of all customer addresses, so that I can keep shipping informed of where to ship products.

## Acceptance Criteria:
Given that I am on the Addresses page,
Whenever the page is loaded,
Then I see a list of customer addresses (ordered by id).

## Requirements/Validations:
- Frontend
  -  Navigating to the `/addresses` path routes the user to the Addresses page which displays a list of addresses
  - The page displays each address record’s id, address_line_1, address_line_2, city, state, and zip
- Backend
  - The GET `api/customers` API endpoint should return a JSON output (see "Outputs" section below)

## Recommended steps  
1. Create a simple wireframe (styles NOT needed) for the page.
2. Determine what components are needed for the page
3. Create the folder/files for the components, and create static components in each file.
4.  Set up the routes needed to route the user to the placeholder components 
5. Add state/props and other functionality to your components.
6. Since your backend is not likely built yet while you're creating the front-end, you can add test data to `db.json` and use the fake `json-server` API instead.
7. Build out the backend. Using code first, set up ONE table (addresses) in the database. Create the API endpoint to get all addresses.
8. Update the front-end to call the real backend API. Make sure everything works.
9. When everything is working, style your application. Follow the [style guide](https://github.com/amex-bootcamp/final-capstone-client#style-guide)
10. Refactor your code, as needed.

## Inputs:
None

## Outputs:
The API GET api/addresses will return a status code of 200 and a set of all address record(s) as JSON:

```json
[
    {
      "id": 1,
      "address_line_1": "06 Memorial Junction",
      "address_line_2": "628",
      "city": "Bedadung Kulon",
      "state": "CA",
      "zip": "18803"
    },
    {
      "id": 2,
      "address_line_1": "471 Basil Avenue",
      "address_line_2": "69084",
      "city": "Shijie",
      "state": "OH",
      "zip": "75070"
    },
    {
      "id": 3,
      "address_line_1": "3722 Toban Parkway",
      "address_line_2": "422",
      "city": "Plymouth",
      "state": "NY",
      "zip": "58317"
    },
    {
      "id": 4,
      "address_line_1": "6391 Linden Junction",
      "address_line_2": "3711",
      "city": "Głogówek",
      "state": "NJ",
      "zip": "10349"
    },
    {
      "id": 5,
      "address_line_1": "36 Cottonwood Parkway",
      "address_line_2": "71",
      "city": "Weitang",
      "state": "WA",
      "zip": "42744"
    }
  ]
```

## Resources
- [React Recipe](https://gist.github.com/kchia/6b4b2790cb854bc12cc2fcbc1f88eb80#react-recipe)
- Use [React Hooks](https://reactjs.org/docs/hooks-intro.html)
  - [React Getting Starter - The Basics](https://app.pluralsight.com/course-player?clipId=a028fa58-7f10-4613-9d46-0b4885bba5a7)
  - [The Star Match Game](https://app.pluralsight.com/course-player?clipId=63738d79-4218-4d2d-9416-72356e963912)
 - [Testing React Applications with Jest](https://app.pluralsight.com/course-player?clipId=ab89a558-23c0-42e2-aaf6-2010eee9fc6c)
- [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/)
- [Running Tests](https://create-react-app.dev/docs/running-tests/)

**Comment by kchia** [comment]
<img width="650" alt="user-story-1" src="https://user-images.githubusercontent.com/7776562/126086094-db140734-b3e0-48e3-bfeb-5e37642e4a7f.png">

**Comment by ivwu** [comment]
![Screen Shot 2021-07-20 at 1 48 32 PM](https://user-images.githubusercontent.com/83653889/126371499-694890e7-23c8-48cb-926b-5d45d363a696.png)

**Comment by ivwu** [comment]
![Screen Shot 2021-07-20 at 2 05 17 PM](https://user-images.githubusercontent.com/83653889/126373507-fea8aa4f-0fda-40c5-9715-d20ce4904aa7.png)
