### ISSUE TITLE
User-story-11 Pagination for the Customers page

### ISSUE THREAD

**Issue by kchia** [Kiresorg/amex-demo-server#11]
# User-story-11 Pagination for the Customers page
As a CSR, I would like to view a list of the most recently added customers, so that I can follow up with them regarding their orders.

## Acceptance Criteria:
Given that I am on the Customers page,
Whenever the page is loaded,
Then I see a list of the X most recently added customers 
And I can click on a “Next” button to load the next X customers onto the page

### Frontend:
- The user should be able to select the number of customer records to load, up to 10, from a drop down menu
- The “Next” button stays active until the user has  paged through all the customers stored in the database
### Backend
- The API GET endpoint `api/customers` will return a status code of 200 and a set of customer record(s) that meet the search query as JSON (see the "Outputs" section below).

## Inputs:
A query string

## Outputs:
The API GET endpoint `api/customers` will return a status code of 200 and a set of customer record(s) that meet the search query as JSON.

## Recommended steps  
1. Create a simple wireframe (styles NOT needed) for the page.
2. Determine what components are needed for the page
3. Create the folder/files for the components, and create static components in each file.
4.  Set up the routes needed to route the user to the placeholder components 
5. Add state/props and other functionality to your components.
6. Since your backend is not likely built yet while you're creating the front-end, you can add test data to `db.json` and use the fake `json-server` API instead.
7. Build out the backend.
8. Update the front-end to call the real backend API. Make sure everything works.
9. When everything is working, style your application. Follow the [style guide](https://github.com/amex-bootcamp/final-capstone-client#style-guide)
10. Refactor your code, as needed.

## Resources
- [React Recipe](https://gist.github.com/kchia/6b4b2790cb854bc12cc2fcbc1f88eb80#react-recipe)
- Use [React Hooks](https://reactjs.org/docs/hooks-intro.html)
  - [React Getting Starter - The Basics](https://app.pluralsight.com/course-player?clipId=a028fa58-7f10-4613-9d46-0b4885bba5a7)
  - [The Star Match Game](https://app.pluralsight.com/course-player?clipId=63738d79-4218-4d2d-9416-72356e963912)
 - [Testing React Applications with Jest](https://app.pluralsight.com/course-player?clipId=ab89a558-23c0-42e2-aaf6-2010eee9fc6c)
- [Testing React Components](https://app.pluralsight.com/library/courses/testing-react-components/table-of-contents)
- [Running Tests](https://create-react-app.dev/docs/running-tests/)

**Comment by andreups** [comment]
![User_Story_11](https://user-images.githubusercontent.com/83587778/126395773-70f1970f-c35d-4f37-9ea5-abb7b2fdb806.png)

**Comment by solid-swan** [comment]
mimi and danny

**Comment by JoycesCodes** [comment]
![image](https://user-images.githubusercontent.com/83613954/126537288-06d1e1df-2976-46d6-9f6b-dd07c5d49d3d.png)
