### ISSUE TITLE
User-story-2: Create a new address

### ISSUE THREAD

**Issue by kchia** [Kiresorg/amex-demo-server#2]
# User-story-2: Create a new address
As a CSR, I would like to create a new address when a new customer calls in to place an order, so that I know where to ship the order.

## Acceptance Criteria:
Given that I am on the New Address page,
When I submit a customer’s address using the form,
Then I am redirected to the Addresses page and see the new address being added to the list of existing customers

### Frontend
- Navigating to the `/addresses/new` path should route the user to the New Address page, which displays a form to collect and submit the address information for a new customer
### Backend
- If the operation is successful, the API endpoint POST `api/customers` should return a status code of `201` and a record of the newly added customer as JSON (see "Outputs" section below).

## Inputs:
I can submit the following information:
- Address line 1
- Address line 2
- City
- State
- zip

## Outputs:
If the operation is successful, the API endpoint POST `api/customers` will return a status code of `201` and a record of the newly added customer as JSON:

```json
{
  "id": 11,
  "address_line_1": "06 Memorial Junction",
  "address_line_2": "628",
  "city": "Belalong Kulon",
  "state": "CA",
  "zip": 18803
}
```

## Recommended steps  
1. Create a simple wireframe (styles NOT needed) for the page.
2. Determine what components are needed for the page
3. Create the folder/files for the components, and create static components in each file.
4.  Set up the routes needed to route the user to the placeholder components 
5. Add state/props and other functionality to your components.
6. Since your backend is not likely built yet while you're creating the front-end, you can add test data to `db.json` and use the fake `json-server` API instead.
7. Build out the backend. 
8. Update the front-end to call the real backend API. Make sure everything works.
9. When everything is working, style your application. Follow the [style guide](https://github.com/amex-bootcamp/final-capstone-client#style-guide)
10. Refactor your code, as needed.

## Resources
- [React Recipe](https://gist.github.com/kchia/6b4b2790cb854bc12cc2fcbc1f88eb80#react-recipe)
- Use [React Hooks](https://reactjs.org/docs/hooks-intro.html)
  - [React Getting Starter - The Basics](https://app.pluralsight.com/course-player?clipId=a028fa58-7f10-4613-9d46-0b4885bba5a7)
  - [The Star Match Game](https://app.pluralsight.com/course-player?clipId=63738d79-4218-4d2d-9416-72356e963912)
 - [Testing React Applications with Jest](https://app.pluralsight.com/course-player?clipId=ab89a558-23c0-42e2-aaf6-2010eee9fc6c)
- [Testing React Components](https://app.pluralsight.com/library/courses/testing-react-components/table-of-contents)
- [Running Tests](https://create-react-app.dev/docs/running-tests/)

**Comment by ivwu** [comment]
![Screen Shot 2021-07-20 at 1 52 07 PM](https://user-images.githubusercontent.com/83653889/126371938-4af7d637-81ff-467a-869d-0436eeba2b6c.png)

**Comment by ivwu** [comment]
![Screen Shot 2021-07-20 at 2 07 49 PM](https://user-images.githubusercontent.com/83653889/126373816-54b50dad-6563-432b-9fbd-d89a8eb7cd53.png)
