### ISSUE TITLE
User-story-6: Create a new customer

### ISSUE THREAD

**Issue by kchia** [Kiresorg/amex-demo-server#6]
# User-story-6: Create a new customer
As a CSR, I would like to create a customer record when a new customer calls in to place an order, so that I have relevant information about every customer.

## Acceptance Criteria:
Given that I am on the New Customer page,
When I submit a customer’s information using the form,
Then I am redirected to the Customers page and see the new customer being added to the list of existing customers

### Frontend
- Navigating to the `/customers/new` path should route to the New Customer page, which displays a form to collect and submit data (including address information) for a new customer
### Backend
- I can only add the new customer if the customer does not already exist in the database (based on phone or email)
- If the operation is successful, the API endpoint POST `api/customers` will return a status code of `201` and a record of the newly added customer as JSON (see the "Outputs" section below).

## Inputs:
A customer record has the following attributes:
- first_name (string, required)
- middle_name (string, optional)
- last_name (string, required)
- phone (string, required)
- email (string, required)
- notes (string, optional)
- address (dropdown menu loading the addresses that the CSR can choose from to associate with the customer)

## Outputs:
If the operation is successful, the API endpoint POST `api/customers` will return a status code of `201` and a record of the newly added customer as JSON:

```json
{
  "id": 1,
  "first_name": "Bernadine",
  "middle_name": "Ulysses",
  "last_name": "Ownsworth",
  "phone": "516-768-8190",
  "email": "uownsworth0@cocolog-nifty.com",
  "notes": "Curabitur convallis.",
  "address_id": 10
}
```

## Recommended steps  
1. Create a simple wireframe (styles NOT needed) for the page.
2. Determine what components are needed for the page
3. Create the folder/files for the components, and create static components in each file.
4.  Set up the routes needed to route the user to the placeholder components 
5. Add state/props and other functionality to your components.
6. Since your backend is not likely built yet while you're creating the front-end, you can add test data to `db.json` and use the fake `json-server` API instead.
7. Build out the backend.
8. Update the front-end to call the real backend API. Make sure everything works.
9. When everything is working, style your application. Follow the [style guide](https://github.com/amex-bootcamp/final-capstone-client#style-guide)
10. Refactor your code, as needed.
## Resources
- [React Recipe](https://gist.github.com/kchia/6b4b2790cb854bc12cc2fcbc1f88eb80#react-recipe)
- Use [React Hooks](https://reactjs.org/docs/hooks-intro.html)
  - [React Getting Starter - The Basics](https://app.pluralsight.com/course-player?clipId=a028fa58-7f10-4613-9d46-0b4885bba5a7)
  - [The Star Match Game](https://app.pluralsight.com/course-player?clipId=63738d79-4218-4d2d-9416-72356e963912)
 - [Testing React Applications with Jest](https://app.pluralsight.com/course-player?clipId=ab89a558-23c0-42e2-aaf6-2010eee9fc6c)
- [Testing React Components](https://app.pluralsight.com/library/courses/testing-react-components/table-of-contents)
- [Running Tests](https://create-react-app.dev/docs/running-tests/)

**Comment by andreups** [comment]
![User_Story_6](https://user-images.githubusercontent.com/83587778/126395925-d2036490-859a-4dec-8d92-eaa5f11fe18e.png)

**Comment by ning9402** [comment]
CLAIMED BY NING AND MOE
